# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/07c5bab4-e5e9-476d-bd8c-3955b1ba3a0b";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/07c5bab4-e5e9-476d-bd8c-3955b1ba3a0b";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/07c5bab4-e5e9-476d-bd8c-3955b1ba3a0b";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/770D-7F48";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  boot.supportedFilesystems = [ "ntfs" ];

  fileSystems."/mnt/1" =
    { device = "/dev/disk/by-uuid/C6E62E01E62DF1FB";
      fsType = "ntfs-3g"; 
      options = [ "rw" "uid=1000" "nofail"];
    };

  fileSystems."/mnt/2" =
    { device = "/dev/disk/by-uuid/2A683C46683C1355";
      fsType = "ntfs-3g"; 
      options = [ "rw" "uid=1000" "nofail"];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.amdgpu.overdrive.enable = true;
}
